<script lang="ts">
  /**
   * Bare image view for `?format=svg|png|pdf` — the diagram alone, no editor.
   *
   * The page itself is served as `text/html`; a static host cannot be made to
   * return `image/svg+xml`. But the browser will happily open a blob it creates
   * locally, and a blob's type is real: `?format=pdf` builds the PDF here and
   * hands it to the browser's own PDF viewer, so opening the link genuinely
   * shows a PDF. What that does *not* do is make the URL fetchable as PDF bytes
   * by an external tool — the first response is still HTML.
   */
  import { onMount } from 'svelte'
  import { render } from './core/index'
  import { downloadPDF, downloadPNG, downloadSVG, pngDataUrl, svgToPdfBlob } from './lib/export'
  import { renderOptionsFrom, type DiagramParams } from './core/url'

  const { params }: { params: DiagramParams } = $props()

  const result = $derived.by(() => {
    try {
      return { ok: true as const, ...render(params.source, renderOptionsFrom(params)) }
    } catch (err) {
      return { ok: false as const, message: (err as Error).message }
    }
  })

  let png = $state<string | null>(null)
  let pdf = $state<string | null>(null)
  let assetError = $state<string | null>(null)

  $effect(() => {
    if (params.format !== 'png' || !result.ok) return
    let cancelled = false
    pngDataUrl(result.svg, params.scale ?? 3)
      .then((url) => !cancelled && (png = url))
      .catch((err: Error) => !cancelled && (assetError = err.message))
    return () => {
      cancelled = true
    }
  })

  $effect(() => {
    if (params.format !== 'pdf' || !result.ok) return
    let cancelled = false
    let url: string | null = null
    svgToPdfBlob(result.svg)
      .then((blob) => {
        if (cancelled) return
        // The blob really is application/pdf, so the browser renders it with
        // its built-in viewer, download and print controls included.
        url = URL.createObjectURL(blob)
        pdf = url
      })
      .catch((err: Error) => !cancelled && (assetError = err.message))
    return () => {
      cancelled = true
      if (url) URL.revokeObjectURL(url)
    }
  })

  onMount(() => {
    if (!params.download || !result.ok) return
    const name = result.kind === 'circuit' ? 'circuit' : 'misty-state'
    if (params.format === 'png') void downloadPNG(result.svg, name, params.scale ?? 3)
    else if (params.format === 'pdf') void downloadPDF(result.svg, name)
    else downloadSVG(result.svg, name)
  })

  const title = $derived(result.ok ? `Misty States — ${result.kind}` : 'Misty States — error')
</script>

<svelte:head>
  <title>{title}</title>
</svelte:head>

{#if !result.ok}
  <div class="flex min-h-full items-center justify-center p-4">
    <pre
      class="max-w-full overflow-x-auto rounded border border-red-200 bg-red-50 px-3 py-2
             font-mono text-sm text-red-700">{result.message}</pre>
  </div>
{:else if assetError}
  <div class="flex min-h-full items-center justify-center p-4">
    <pre
      class="rounded border border-red-200 bg-red-50 px-3 py-2 font-mono text-sm
             text-red-700">{assetError}</pre>
  </div>
{:else if params.format === 'pdf'}
  {#if pdf}
    <iframe src={pdf} title={title} class="h-screen w-full border-0"></iframe>
  {:else}
    <p class="flex min-h-full items-center justify-center text-sm text-slate-400">
      Building PDF…
    </p>
  {/if}
{:else if params.format === 'png'}
  <div class="flex min-h-full items-center justify-center p-4">
    {#if png}
      <!-- An <img> so the browser's own "Save image as…" yields a PNG. -->
      <img src={png} alt="Quantum diagram" class="h-auto max-w-full" />
    {:else}
      <p class="text-sm text-slate-400">Rendering…</p>
    {/if}
  </div>
{:else}
  <div class="flex min-h-full items-center justify-center p-4">
    <!-- Generated by our own renderer; all values are escaped in svg.ts. -->
    {@html result.svg}
  </div>
{/if}
